config/routes.rb
ShippingRates::Application.routes.draw do
  root 'rates#new'

  resources :rates

  

  

end

app/models/rate.rb
class Rate < ActiveRecord::Base

	validates :weight, numericality: { :greater_than => 0 }
	validates_format_of :zip, :with => /^\d{5}(-\d{4})?$/, multiline: true, :message => "should be in the form 12345 or 12345-1234"

	validate :zip_code_must_match_state

	def zip_code_must_match_state
		unless self.state == ZipCodeInfo.instance.state_for( self.zip )
			 errors.add(:zip, "is not valid for the state specified")
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rates_controller.rb
require 'active_shipping'
include ActiveMerchant::Shipping

class RatesController < ApplicationController
  def index
  end

  def new
  	@rate = Rate.new
  end

  def create
  	@rate = Rate.new(post_params)

 	if 	@rate.save
  		redirect_to @rate
  	else
  		render "new"
  	end
  end

  def show
  	@rate = Rate.find(params[:id])

  	@packages = [ Package.new( @rate.weight, [10,10,10], :units => :imperial ) ]

	@origin = Location.new(  :country => 'US',
                            :state => 'CA',
                            :city => 'Palo Alto',
                            :zip => '94306')

	@destination = Location.new( :country => @rate.country,
                            :state => @rate.state,
                            :city => @rate.city,
                            :zip => @rate.zip )

	#UPS
	ups = UPS.new(:login => 'massdroptest', :password => 'mansion92', :key => '8CC2BEE7ED40B8D5')
	@upsResponse = ups.find_rates(@origin, @destination, @packages)

	# #FEDEX
	# key Og9RdpcHV3S0NVeV
	fedex = FedEx.new(:login => '118588852', :password => 'vsLFxEkmsPENTN5Rq9Omc4oym', key: 'Og9RdpcHV3S0NVeV', account: '510087160', test: true)
	@fedexResponse = fedex.find_rates(@origin, @destination, @packages)

	# #USPS
	 usps = USPS.new(:login => '012MASSD7511')
	 @uspsResponse = usps.find_rates(@origin, @destination, @packages)

  end

private
  def post_params
    params.require(:rate).permit(:weight, :country, :state, :city, :zip)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rates_helper.rb
module RatesHelper

	def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShippingRates</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rates/_form.html.erb
<%= form_for :rate, url: rates_path do |f| %>
    <% if @rate.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@rate.errors.count, "error") %> prohibited this app from checking rates:</h2>
 
    <ul>
    <% @rate.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


    <div class="field">
        <%= f.text_field :weight, :placeholder => "Weight (ounces)" %>
    </div>

    <div class="field">
        <%= f.country_select :country, ["United States"] %>
        <%#= f.text_field :country, :placeholder => "Country" %>
    </div>

    <br />
    <p>The following fields only apply to US destinations</p>

    <div class="field">
        <%= f.select :state, options_for_select(us_states) %>
    </div>

    <div class="field">
        <%= f.text_field :city, :placeholder => "City" %>
    </div>

    <div class="field">
        <%= f.text_field :zip, :placeholder => "Zip" %>
    </div>

    <div class="action">
        <%= f.submit "Find rates" %>
    </div>
<% end %>

app/views/rates/index.html.erb
<h1>Shipping Rates</h1>

app/views/rates/new.html.erb
<h1>New Rate</h1>

<%= render 'form', :url=> { :action => :create } %>

app/views/rates/show.html.erb
<H1>Package Info</H1>

<ul>
  <li>
  <p>
    <strong>Weight:</strong>
    <%= pluralize(@rate.weight, "ounce") %> 
  </p>
  </li>

  <li>
  <p>
    <strong>Country:</strong>
    <%= @rate.country %>
  </p>
  </li>
   
  <% if @rate.country == "United States" %>
    <li>
  	<p>
  	  <strong>State:</strong>
  	  <%= @rate.state %>
  	</p>
    </li>
  <% end %>

  <% unless @rate.city == "" %>
    <li>
  	<p>
  	  <strong>City:</strong>
  	  <%= @rate.city %>
  	</p>
    </li>
  <% end %>

  <% if @rate.country == "United States" %>
    <li>
  	<p>
  	  <strong>Zip Code:</strong>
  	  <%= @rate.zip %>
  	</p>
    </li>
  <% end %>
</ul>

<h1>Shipping Rates</h1>

<p>
  <strong>UPS:</strong><br />
  <ul>
    <% upsRates = @upsResponse.rates.sort_by(&:price).collect %>
    <% upsRates.each do |rate| %>
    	<li><%= rate.service_name %>: $<%= rate.price / 100.0 %></li>
    	<br />
    <% end %>
  </ul>
</p>

 <p>
  <strong>FedEx:</strong><br />
  <ul>
    <% fedexRates = @fedexResponse.rates.sort_by(&:price).collect %>
    <% fedexRates.each do |rate| %>
      <li><%= rate.service_name %>: $<%= rate.price / 100.0 %></li>
      <br />
    <% end %>
  </ul>
</p>


<p>
  <strong>USPS:</strong><br />
  <ul>
    <% uspsRates = @uspsResponse.rates.sort_by(&:price).collect %>
    <% uspsRates.each do |rate| %>
    	<li><%= rate.service_name %>: $<%= rate.price / 100.0 %></li>
    	<br />
    <% end %>
  </ul>
</p> 


<%= link_to("Back", "/" ) %>